stages:
  - code_quality
  - test
  - build
  - deploy

eslint:
  image: node:10.15.0
  stage: code_quality
  before_script:
    - yarn install
  script:
    - yarn lint
unit_tests:
  image: node:10.15.0
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test a
react_build:
  image: node:10.15.0
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build
pages:
  stage: deploy
  script:
    - CI=true npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master