unit_tests:
  image: node:10.15.0
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test a
react_build:
  image: node:10.15.0
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build

